baseURL = "https://1917dc.github.io/"  # please update this to your actual URL
languageCode = "pt-br"
title = "Café & Tapioca"
theme = "hugo-sputnik"

[permalinks]
note = "/note/:year/:month/:day/:slug/"
post = "/post/:year/:month/:day/:slug/"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40



[taxonomies]
  tag = 'tags'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  [params.bio]
    name = 'Author Name'
    theme = 'Hugo Sputnik'
    startYear = '2024'
    
  [params.social]
    github = 'https://github.com/1917dc'
    lastfm = 'https://www.last.fm/user/gfxnx'
    letterboxd = 'https://letterboxd.com/yyounevershould/'
    instagram = 'https://www.instagram.com/1917.dc/'

  [params.contact]
    email = 'mailto:19051997@gmail.com'

  [params.logo]
    image = '/logo.png'
  
  [params.favicon]
    icon = '/favicon.ico'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
  
[markup]
[markup.highlight]
codeFences = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [["\\[", "\\]"], ["$$", "$$"]]
inline = [["\\(", "\\)"]]
