name = 'Hugo Sputnik'
license = 'MIT'
licenselink = 'https://github.com/1917dc/hugo-sputnik/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/1917dc/hugo-sputnik'

# If you have a running demo of the theme
demosite = 'https://1917dc.github.io/hugo-sputnik'

# Taxonomy terms
tags = ['blog']
features = ['simple', 'personal']


# If the theme has a single author
[author]
  name = '1917dc'
  homepage = 'https://github.com/1917dc/blog'